// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>
#include "BloomFilter.h"

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_filter_keys
LogicalVector rcpp_filter_keys(IntegerVector y_keys, IntegerVector x_keys, size_t expected_elements, double false_positive_rate);
RcppExport SEXP _bloomjoin_rcpp_filter_keys(SEXP y_keysSEXP, SEXP x_keysSEXP, SEXP expected_elementsSEXP, SEXP false_positive_rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type y_keys(y_keysSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type x_keys(x_keysSEXP);
    Rcpp::traits::input_parameter< size_t >::type expected_elements(expected_elementsSEXP);
    Rcpp::traits::input_parameter< double >::type false_positive_rate(false_positive_rateSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_filter_keys(y_keys, x_keys, expected_elements, false_positive_rate));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hash_join_keys
CharacterVector rcpp_hash_join_keys(List columns);
RcppExport SEXP _bloomjoin_rcpp_hash_join_keys(SEXP columnsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type columns(columnsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_hash_join_keys(columns));
    return rcpp_result_gen;
END_RCPP
}
// hash_keys32_cols
IntegerVector hash_keys32_cols(List cols, bool normalize_strings, bool na_sentinel);
RcppExport SEXP _bloomjoin_hash_keys32_cols(SEXP colsSEXP, SEXP normalize_stringsSEXP, SEXP na_sentinelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type cols(colsSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize_strings(normalize_stringsSEXP);
    Rcpp::traits::input_parameter< bool >::type na_sentinel(na_sentinelSEXP);
    rcpp_result_gen = Rcpp::wrap(hash_keys32_cols(cols, normalize_strings, na_sentinel));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_blm_module();

static const R_CallMethodDef CallEntries[] = {
    {"_bloomjoin_rcpp_filter_keys", (DL_FUNC) &_bloomjoin_rcpp_filter_keys, 4},
    {"_bloomjoin_rcpp_hash_join_keys", (DL_FUNC) &_bloomjoin_rcpp_hash_join_keys, 1},
    {"_bloomjoin_hash_keys32_cols", (DL_FUNC) &_bloomjoin_hash_keys32_cols, 3},
    {"_rcpp_module_boot_blm_module", (DL_FUNC) &_rcpp_module_boot_blm_module, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_bloomjoin(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
