# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_filter_keys <- function(y_keys, x_keys, expected_elements, false_positive_rate = 0.01) {
    .Call(`_bloomjoin_rcpp_filter_keys`, y_keys, x_keys, expected_elements, false_positive_rate)
}

rcpp_hash_join_keys <- function(columns) {
    .Call(`_bloomjoin_rcpp_hash_join_keys`, columns)
}

hash_keys32_cols <- function(cols, normalize_strings = TRUE, na_sentinel = TRUE) {
    .Call(`_bloomjoin_hash_keys32_cols`, cols, normalize_strings, na_sentinel)
}

