name: R
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: ['4.1']
    steps:
      - uses: actions/checkout@v4

      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}

      - name: Install pandoc (macOS)
        run: |
          brew install pandoc

      - name: Install TinyTeX
        uses: r-lib/actions/setup-tinytex@v2

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "readr", "kableExtra"), repos = "https://cloud.r-project.org")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Check
        run: |
          rcmdcheck::rcmdcheck(args = "--no-manual --no-build-vignettes --no-vignettes", error_on = "error")
        shell: Rscript {0}
